version: '2'
services:
    epressing-app:
        image: epressing
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://epressing-mysql:3306/epressing?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=epressing-elasticsearch:9300
        ports:
            - 8080:8080
    epressing-mysql:
        extends:
            file: mysql.yml
            service: epressing-mysql
    epressing-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: epressing-elasticsearch
